### PR TITLE
Upgrades kotlin to 1.2.60 and moves detektCheck to the check phase.

### PR DESCRIPTION
**Pull request by coyotesqrl**
#### Checklist:
- [ ] Common Kotlin Unit Tests Added/Modified
- [ ] Javascript Mocha Tests Added to `js-test` module

### CODE REVIEW

**Comment by blen-desta** [comment]
build now

**Comment by blen-desta** [comment]
build now

**Comment by blen-desta** [comment]
build now

**Comment by coyotesqrl** [comment]
build now

**Review by blen-desta — APPROVED** [review]

**Comment by coyotesqrl** [comment]
build now

**Comment by coyotesqrl** [comment]
build now

**Pull request merged**
